The file `IntegerArray.txt` contains all of the 100,000 integers between 1 and 100,000 (inclusive) in some order, with no integer repeated.

Your task is to compute the number of inversions in the file given, where the $i^{th}$ row of the file indicates the $i^{th}$ entry of an array.

Because of the large size of this array, you should implement the fast divide-and-conquer algorithm covered in the video lectures.

TIP: before submitting, first test the correctness of your program on some small test files or your own devising.

In [1]:
import numpy as np

In [7]:
def merge_and_count_split_inv(C, D):
    
    B = np.empty(len(C) + len(D))
    m = len(C)
    lenD = len(D)
    i = 0
    j = 0
    splitInv = 0
    for k in range(len(C) + len(D)): 
        # check if there is no more D
        if (j == lenD and i < m):
            B[k] = C[i]
            i += 1
            continue
            
        elif i == m:
            # copy the rest of D into output array B
            B[k] = D[j]
            j += 1
            splitInv += m - i 
            continue

        else:
            if C[i] < D[j]:
                B[k] = C[i]
                i += 1
            else:
                B[k] = D[j]
                j += 1
                splitInv += m - i
                
    return (B, splitInv)

In [8]:
C = np.array([25260, 60660])
D = np.array([2995])
merge_and_count_split_inv(C, D) 

(array([ 2995., 25260., 60660.]), 2)

In [9]:
C = np.array([14, 29, 54, 79])
D = np.array([2, 25, 53, 60])
merge_and_count_split_inv(C, D) 

(array([ 2., 14., 25., 29., 53., 54., 60., 79.]), 10)

Example 1:

In [10]:
A = [1, 3, 5, 2, 4, 6]
C = A[: len(A) // 2]
D = A[len(A) // 2 :]
print(C, D)
merge_and_count_split_inv(C, D)

[1, 3, 5] [2, 4, 6]


(array([1., 2., 3., 4., 5., 6.]), 3)

Example 2:

In [11]:
C = np.array([0, 1])
D = np.array([2])
print(C, D)
merge_and_count_split_inv(C, D)

[0 1] [2]


(array([0., 1., 2.]), 0)

Example 3:

In [18]:
def sort_and_count_inv(A):
    n = np.int( len( A ))
    
    # stop cases
    if n < 2:
        return (A, 0)
    
    # base case
    elif n == 2:
        aa = np.empty(2)
        if A[1] < A[0]:
            aa[0] = A[1]
            aa[1] = A[0]
            return (aa, 1)
        else:
            return (A, 0)
    
    # if n is odd
    elif n % 2 != 0:
        # return sorted first half of A
        (C, leftInv) = sort_and_count_inv(A[: n // 2 + 1 ])
        (D, rightInv) = sort_and_count_inv(A[n // 2 + 1 :])
        (B, splitInv) = merge_and_count_split_inv(C, D)
        
        return (B, leftInv + rightInv + splitInv)
    
    else:
        # return sorted first half of A
        (C, leftInv) = sort_and_count_inv(A[: n // 2])
        # return sorted second hald of A
        (D, rightInv) = sort_and_count_inv(A[n // 2 :])
        # return sorted input array A and number of split inversions
        (B, splitInv) = merge_and_count_split_inv(C, D)
        
        return (B, leftInv + rightInv + splitInv)

In [19]:
print(A)
sort_and_count_inv(A)

[54044 14108 79294 29649 25260 60660  2995 53777]


(array([ 2995., 14108., 25260., 29649., 53777., 54044., 60660., 79294.]), 16)

Example 2:

In [20]:
a = np.fromfile('IntegerArray.txt', sep='\n', dtype=np.int)
a = a[:4]
a

array([54044, 14108, 79294, 29649])

In [21]:
sort_and_count_inv(a)

(array([14108., 29649., 54044., 79294.]), 3)

Example 2:

In [22]:
A = np.fromfile('IntegerArray.txt', sep='\n', dtype=np.int)
A = A[:8]
print(A)
sort_and_count_inv(A)

[54044 14108 79294 29649 25260 60660  2995 53777]


(array([ 2995., 14108., 25260., 29649., 53777., 54044., 60660., 79294.]), 16)

Example 3:

In [23]:
a = np.fromfile('IntegerArray.txt', sep='\n', dtype=np.int)
sort_and_count_inv(a)

(array([1.0000e+00, 2.0000e+00, 3.0000e+00, ..., 9.9998e+04, 9.9999e+04,
        1.0000e+05]), 2407905288)

In [2]:
def Merge(C, D):
    B = np.empty(len(C)*2)
    m = len(C)
    i = 0
    j = 0
    
    for k in range(len(C)*2):
        print(i, j, k)
        if i == m:
            # copy the rest of D into output array B
            B[k] = D[j]
            j += 1
            continue
        elif j == m:
            # copy the rest of C into output array B
            B[k] = C[i]
            i += 1
            continue
        else:
            if C[i] < D[j]:
                B[k] = C[i]
                i += 1
            else:
                B[k] = D[j]
                j += 1
                
    return B

In [3]:
C = np.array([1, 2, 6, 8])
D = np.array([3, 4, 5, 7])

Merge(C, D)

0 0 0
1 0 1
2 0 2
2 1 3
2 2 4
2 3 5
3 3 6
3 4 7


array([1., 2., 3., 4., 5., 6., 7., 8.])

In [4]:
def MergeSort(A):
    
    n = np.int( len(A) )
    print('n: ', n)
    # base case
    if n < 2:
        return A
    
    
    else:
    
        # recursively sort first half of A
        C = MergeSort(A[: n // 2])
        print('C: ', C)
        # recursively sort second half of A
        D = MergeSort(A[n // 2 :])
        print('D: ', D)
        
        
        return Merge(C, D)

Example 1:

In [5]:
A = np.fromfile('IntegerArray.txt', sep='\n', dtype=np.int)
A = A[:4]
A

array([54044, 14108, 79294, 29649])

In [6]:
MergeSort(A)

n:  4
n:  2
n:  1
C:  [54044]
n:  1
D:  [14108]
0 0 0
0 1 1
C:  [14108. 54044.]
n:  2
n:  1
C:  [79294]
n:  1
D:  [29649]
0 0 0
0 1 1
D:  [29649. 79294.]
0 0 0
1 0 1
1 1 2
2 1 3


array([14108., 29649., 54044., 79294.])